/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAllTasksRouteImport } from './routes/app.all-tasks'
import { Route as AppAboutRouteImport } from './routes/app.about'
import { Route as AppTaskIdRouteImport } from './routes/app.$taskId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAllTasksRoute = AppAllTasksRouteImport.update({
  id: '/all-tasks',
  path: '/all-tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppTaskIdRoute = AppTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$taskId': typeof AppTaskIdRoute
  '/app/about': typeof AppAboutRoute
  '/app/all-tasks': typeof AppAllTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$taskId': typeof AppTaskIdRoute
  '/app/about': typeof AppAboutRoute
  '/app/all-tasks': typeof AppAllTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$taskId': typeof AppTaskIdRoute
  '/app/about': typeof AppAboutRoute
  '/app/all-tasks': typeof AppAllTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/app/$taskId' | '/app/about' | '/app/all-tasks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/app/$taskId' | '/app/about' | '/app/all-tasks'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/$taskId'
    | '/app/about'
    | '/app/all-tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/all-tasks': {
      id: '/app/all-tasks'
      path: '/all-tasks'
      fullPath: '/app/all-tasks'
      preLoaderRoute: typeof AppAllTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/about': {
      id: '/app/about'
      path: '/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$taskId': {
      id: '/app/$taskId'
      path: '/$taskId'
      fullPath: '/app/$taskId'
      preLoaderRoute: typeof AppTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppTaskIdRoute: typeof AppTaskIdRoute
  AppAboutRoute: typeof AppAboutRoute
  AppAllTasksRoute: typeof AppAllTasksRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppTaskIdRoute: AppTaskIdRoute,
  AppAboutRoute: AppAboutRoute,
  AppAllTasksRoute: AppAllTasksRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
